add_newline = false # remove a line at top
prompt_order = [
    "username", "hostname", "directory", "git_branch", "git_state", "nodejs", "python", "ruby", "golang",
    "memory_usage", "jobs", "line_break", "character"
    ]

[memory_usage]
disabled = false
show_percentage = true

[jobs]
disabled = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[golang]
symbol = "ğŸğŸ’¨ "

[directory]
style = "fg:#98C379"
