add_newline = false # remove a line at top

format = """
$directory$git_branch$kubernetes$golang$java$ruby$nodejs$python
$character
"""

[jobs]
disabled = false

[golang]
symbol = "ğŸğŸ’¨ "

[directory]
style = "fg:#98C379"
